// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/SergeiGD/golang-template/config"
	"github.com/SergeiGD/golang-template/internal/adapter/sql/wallets"
	"github.com/SergeiGD/golang-template/internal/services"
	"github.com/SergeiGD/golang-template/internal/usecases"
	"github.com/SergeiGD/golang-template/pkg/logger"
)

// Injectors from wire.go:

func InitializeWalletRepo(cfg config.Config, logger2 *logger.Logger) (wallets.WalletsRepository, error) {
	walletsRepository, err := ProvideWalletsRepository(cfg, logger2)
	if err != nil {
		return nil, err
	}
	return walletsRepository, nil
}

func InitializeWalletService(repo wallets.WalletsRepository, cfg config.Config, logger2 *logger.Logger) services.WalletsService {
	walletsService := ProvideWalletsService(repo, logger2)
	return walletsService
}

func InitializeLimiterService(cfg config.Config) services.WalletRateLimiter {
	walletRateLimiter := ProvideLimiterService(cfg)
	return walletRateLimiter
}

func InitializeWalletUseCases(service services.WalletsService, limiter services.WalletRateLimiter, cfg config.Config, logger2 *logger.Logger) usecases.WalletsUseCases {
	walletsUseCases := ProvideWalletsUseCases(service, limiter, logger2)
	return walletsUseCases
}
