// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ResponseError defines model for ResponseError.
type ResponseError struct {
	// Detail Описание ошибки
	Detail string `json:"detail"`
}

// Wallet Схема предмета
type Wallet struct {
	Balance   float32   `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
}

// N404NotFound defines model for 404NotFound.
type N404NotFound = ResponseError

// N40xError defines model for 40xError.
type N40xError = ResponseError

// N50xError defines model for 50xError.
type N50xError = ResponseError

// WalletOperationJSONBody defines parameters for WalletOperation.
type WalletOperationJSONBody struct {
	// Amount сумма
	Amount float32 `json:"amount" validate:"gte=0"`

	// OperationType тип операции
	OperationType string             `json:"operation_type"`
	WalletId      openapi_types.UUID `json:"wallet_id"`
}

// WalletOperationJSONRequestBody defines body for WalletOperation for application/json ContentType.
type WalletOperationJSONRequestBody WalletOperationJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Операция с кошельком
	// (POST /api/v1/wallets/)
	WalletOperation(c *gin.Context)
	// Получение кошелька
	// (GET /api/v1/wallets/{id}/)
	GetWalletById(c *gin.Context, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// WalletOperation operation middleware
func (siw *ServerInterfaceWrapper) WalletOperation(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.WalletOperation(c)
}

// GetWalletById operation middleware
func (siw *ServerInterfaceWrapper) GetWalletById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWalletById(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/wallets/", wrapper.WalletOperation)
	router.GET(options.BaseURL+"/api/v1/wallets/:id/", wrapper.GetWalletById)
}

type N404NotFoundJSONResponse ResponseError

type N40xErrorJSONResponse ResponseError

type N50xErrorJSONResponse ResponseError

type WalletOperationRequestObject struct {
	Body *WalletOperationJSONRequestBody
}

type WalletOperationResponseObject interface {
	VisitWalletOperationResponse(w http.ResponseWriter) error
}

type WalletOperation200JSONResponse Wallet

func (response WalletOperation200JSONResponse) VisitWalletOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type WalletOperation404JSONResponse struct{ N404NotFoundJSONResponse }

func (response WalletOperation404JSONResponse) VisitWalletOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type WalletOperation500JSONResponse struct{ N50xErrorJSONResponse }

func (response WalletOperation500JSONResponse) VisitWalletOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type WalletOperationdefaultJSONResponse struct {
	Body       ResponseError
	StatusCode int
}

func (response WalletOperationdefaultJSONResponse) VisitWalletOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetWalletByIdRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetWalletByIdResponseObject interface {
	VisitGetWalletByIdResponse(w http.ResponseWriter) error
}

type GetWalletById200JSONResponse Wallet

func (response GetWalletById200JSONResponse) VisitGetWalletByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWalletById404JSONResponse struct{ N404NotFoundJSONResponse }

func (response GetWalletById404JSONResponse) VisitGetWalletByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetWalletById500JSONResponse struct{ N50xErrorJSONResponse }

func (response GetWalletById500JSONResponse) VisitGetWalletByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetWalletByIddefaultJSONResponse struct {
	Body       ResponseError
	StatusCode int
}

func (response GetWalletByIddefaultJSONResponse) VisitGetWalletByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Операция с кошельком
	// (POST /api/v1/wallets/)
	WalletOperation(ctx context.Context, request WalletOperationRequestObject) (WalletOperationResponseObject, error)
	// Получение кошелька
	// (GET /api/v1/wallets/{id}/)
	GetWalletById(ctx context.Context, request GetWalletByIdRequestObject) (GetWalletByIdResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// WalletOperation operation middleware
func (sh *strictHandler) WalletOperation(ctx *gin.Context) {
	var request WalletOperationRequestObject

	var body WalletOperationJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.WalletOperation(ctx, request.(WalletOperationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "WalletOperation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(WalletOperationResponseObject); ok {
		if err := validResponse.VisitWalletOperationResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWalletById operation middleware
func (sh *strictHandler) GetWalletById(ctx *gin.Context, id openapi_types.UUID) {
	var request GetWalletByIdRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWalletById(ctx, request.(GetWalletByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWalletById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetWalletByIdResponseObject); ok {
		if err := validResponse.VisitGetWalletByIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWzY7jRBB+lajh6Ky9MEgrSxxYCdBcAHHhgKJRj13J9Mp2m3Z7mCiKNJkVsBJI3JFg",
	"hHiBYdhow/wkr1D9RqjKcRInGTL7c5xL5LS7qr766qsqD0Sk01xnkNlChANhoMh1VgD/2Qv2vtD2M11m",
	"Mf2NdGYhs/Qo8zxRkbRKZ/6zQmd0BicyzZPKctWsKNNUmr4IBf6O4xbe4gX+iy9xjLc4FZ44lkkJdDEG",
	"K1Vyx73hcOiJIjqCVNLd9w10RSje85fw/ept4X89z+FTY7SpDGMoIqNywnuXf0/sBSeVyevlurBZSfQP",
	"9wIn+Dde4UULL3Hawkt3imO8cb/S4884wyle4y0Hn9DhK7zAmTvFqRvhxXZW3tbpO6XwrcF44qMHvt+M",
	"bzfCsTvFS/6lOHUY5qfpKxyI3OgcjFUVfXV+g40IOMMJAadsqEGmi5AT4dUloJvnlCJO8BVfuSZ6iAQ6",
	"IEwjd0bNRYQsXRDHtp+TfWGNynoM28B3pTIQi/DbGlhn6IlvZJKA3YLxT/cDFYAizrgWL/EGx+6M3Tfz",
	"PJSJzCIu6TxuVqaHYEh5kQFpIT6QHKOrTUpPIpYW2lalsBNr7bzhqrOw0ofPILJVHVXW1ZuZfPLVfguv",
	"mJ8xXrtfaoaUZYorAgrSJZiiMnn8KHgUEHqdQyZzJULxIR95Ipf2iJP2Za7848f+95W9z+XXhb2j3Kwf",
	"9yOL143WAU3xRnA0w824Hy+AfVmfiYoWKOxTHffv0cjLdmhWS6a6zLbAdCP3HG+o4suazOvoiZO2lrlq",
	"RzqGHmRtOLFGtq3sscdjmSgqqAhFz8LHAddwkcxB5Wsj3BlOcNbC6So5LP81PXiiovhAxQ0JlaWKd6pn",
	"aerViW9A2y6mpRdrSuCDlX39QRC8Vgn+byLNW3DbKPrLjZieF7Q4aVDwHHTP3U/VJKSjdWnzet27K+gi",
	"C3/1k4NXRLDbZrFHGGpXlom9T6DaiKbnyia5Z1tUMqtrWYgO+Vlvv4GKh9yDva3T7Hwrb3iLVzTbeIpO",
	"8R9aPGt0MuUt1k+zPT8HWxXuaX8/5sFgZAoWDGGlNZonOgYRdmVSAM0mEfLwEJ7IZEpqY6dNma0usR1C",
	"90Rh+zzBCsXbYth50Og71+j57ly2CpS8gDmu1dCkLNGRTI5oV3iiNPQBdGRtHvr+4kX4JHgScEXnvjcE",
	"/VsDxWSpqhrEsDP8LwAA///mLVLccgwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
