// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package wallets

import (
	"context"

	"github.com/SergeiGD/itk_test/internal/models"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWalletsRepository creates a new instance of MockWalletsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletsRepository {
	mock := &MockWalletsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWalletsRepository is an autogenerated mock type for the WalletsRepository type
type MockWalletsRepository struct {
	mock.Mock
}

type MockWalletsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletsRepository) EXPECT() *MockWalletsRepository_Expecter {
	return &MockWalletsRepository_Expecter{mock: &_m.Mock}
}

// DepositToWallet provides a mock function for the type MockWalletsRepository
func (_mock *MockWalletsRepository) DepositToWallet(ctx context.Context, walletId uuid.UUID, amount decimal.Decimal) (*models.WalletModel, error) {
	ret := _mock.Called(ctx, walletId, amount)

	if len(ret) == 0 {
		panic("no return value specified for DepositToWallet")
	}

	var r0 *models.WalletModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.Decimal) (*models.WalletModel, error)); ok {
		return returnFunc(ctx, walletId, amount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.Decimal) *models.WalletModel); ok {
		r0 = returnFunc(ctx, walletId, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WalletModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, decimal.Decimal) error); ok {
		r1 = returnFunc(ctx, walletId, amount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWalletsRepository_DepositToWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DepositToWallet'
type MockWalletsRepository_DepositToWallet_Call struct {
	*mock.Call
}

// DepositToWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - walletId uuid.UUID
//   - amount decimal.Decimal
func (_e *MockWalletsRepository_Expecter) DepositToWallet(ctx interface{}, walletId interface{}, amount interface{}) *MockWalletsRepository_DepositToWallet_Call {
	return &MockWalletsRepository_DepositToWallet_Call{Call: _e.mock.On("DepositToWallet", ctx, walletId, amount)}
}

func (_c *MockWalletsRepository_DepositToWallet_Call) Run(run func(ctx context.Context, walletId uuid.UUID, amount decimal.Decimal)) *MockWalletsRepository_DepositToWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 decimal.Decimal
		if args[2] != nil {
			arg2 = args[2].(decimal.Decimal)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWalletsRepository_DepositToWallet_Call) Return(walletModel *models.WalletModel, err error) *MockWalletsRepository_DepositToWallet_Call {
	_c.Call.Return(walletModel, err)
	return _c
}

func (_c *MockWalletsRepository_DepositToWallet_Call) RunAndReturn(run func(ctx context.Context, walletId uuid.UUID, amount decimal.Decimal) (*models.WalletModel, error)) *MockWalletsRepository_DepositToWallet_Call {
	_c.Call.Return(run)
	return _c
}

// GetWalletById provides a mock function for the type MockWalletsRepository
func (_mock *MockWalletsRepository) GetWalletById(ctx context.Context, walletId uuid.UUID) (*models.WalletModel, error) {
	ret := _mock.Called(ctx, walletId)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletById")
	}

	var r0 *models.WalletModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.WalletModel, error)); ok {
		return returnFunc(ctx, walletId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.WalletModel); ok {
		r0 = returnFunc(ctx, walletId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WalletModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, walletId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWalletsRepository_GetWalletById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWalletById'
type MockWalletsRepository_GetWalletById_Call struct {
	*mock.Call
}

// GetWalletById is a helper method to define mock.On call
//   - ctx context.Context
//   - walletId uuid.UUID
func (_e *MockWalletsRepository_Expecter) GetWalletById(ctx interface{}, walletId interface{}) *MockWalletsRepository_GetWalletById_Call {
	return &MockWalletsRepository_GetWalletById_Call{Call: _e.mock.On("GetWalletById", ctx, walletId)}
}

func (_c *MockWalletsRepository_GetWalletById_Call) Run(run func(ctx context.Context, walletId uuid.UUID)) *MockWalletsRepository_GetWalletById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWalletsRepository_GetWalletById_Call) Return(walletModel *models.WalletModel, err error) *MockWalletsRepository_GetWalletById_Call {
	_c.Call.Return(walletModel, err)
	return _c
}

func (_c *MockWalletsRepository_GetWalletById_Call) RunAndReturn(run func(ctx context.Context, walletId uuid.UUID) (*models.WalletModel, error)) *MockWalletsRepository_GetWalletById_Call {
	_c.Call.Return(run)
	return _c
}

// WithdrawFromWallet provides a mock function for the type MockWalletsRepository
func (_mock *MockWalletsRepository) WithdrawFromWallet(ctx context.Context, walletId uuid.UUID, amount decimal.Decimal) (*models.WalletModel, error) {
	ret := _mock.Called(ctx, walletId, amount)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawFromWallet")
	}

	var r0 *models.WalletModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.Decimal) (*models.WalletModel, error)); ok {
		return returnFunc(ctx, walletId, amount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.Decimal) *models.WalletModel); ok {
		r0 = returnFunc(ctx, walletId, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WalletModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, decimal.Decimal) error); ok {
		r1 = returnFunc(ctx, walletId, amount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWalletsRepository_WithdrawFromWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithdrawFromWallet'
type MockWalletsRepository_WithdrawFromWallet_Call struct {
	*mock.Call
}

// WithdrawFromWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - walletId uuid.UUID
//   - amount decimal.Decimal
func (_e *MockWalletsRepository_Expecter) WithdrawFromWallet(ctx interface{}, walletId interface{}, amount interface{}) *MockWalletsRepository_WithdrawFromWallet_Call {
	return &MockWalletsRepository_WithdrawFromWallet_Call{Call: _e.mock.On("WithdrawFromWallet", ctx, walletId, amount)}
}

func (_c *MockWalletsRepository_WithdrawFromWallet_Call) Run(run func(ctx context.Context, walletId uuid.UUID, amount decimal.Decimal)) *MockWalletsRepository_WithdrawFromWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 decimal.Decimal
		if args[2] != nil {
			arg2 = args[2].(decimal.Decimal)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWalletsRepository_WithdrawFromWallet_Call) Return(walletModel *models.WalletModel, err error) *MockWalletsRepository_WithdrawFromWallet_Call {
	_c.Call.Return(walletModel, err)
	return _c
}

func (_c *MockWalletsRepository_WithdrawFromWallet_Call) RunAndReturn(run func(ctx context.Context, walletId uuid.UUID, amount decimal.Decimal) (*models.WalletModel, error)) *MockWalletsRepository_WithdrawFromWallet_Call {
	_c.Call.Return(run)
	return _c
}
